default:
  schedulingRules:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: nodetype
              operator: In
              values:
              - otel 
opentelemetry-collector:
  resources:
    limits:
      memory: 1Gi
  extraEnvs:
    - name: ELASTIC_APM_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: elastic-secret
          key: elastic_apm_endpoint
    - name: ELASTIC_APM_SECRET_TOKEN
      valueFrom:
        secretKeyRef:
          name: elastic-secret
          key: elastic_apm_secret_token
  config:
    exporters:
      otlp/elastic:
        endpoint: ${ELASTIC_APM_ENDPOINT}
        headers:
          Authorization: Bearer ${ELASTIC_APM_SECRET_TOKEN}
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${MY_POD_IP}:4317
          http:
            cors:
              allowed_origins:
              - http://*
              - https://*
            endpoint: ${MY_POD_IP}:4318
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/elastic]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/elastic]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/elastic]
grafana:
  enabled: false

jaeger:
  enabled: false

prometheus:
  enabled: false

components:
  frontend:
    resources:
      limits:
        memory: 1Gi
  frontendProxy:
    resources:
      limits:
        memory: 1Gi
    service:
      type: LoadBalancer
  quoteService:
    resources:
      limits:
        memory: 1Gi
  checkoutService:
    resources:
      limits:
        memory: 1Gi
  accountingService:
    resources:
      limits:
        memory: 1Gi
  accountingService:
    resources:
      limits:
        memory: 1Gi
